/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Frames;

import Control.ControlNegocio;
import itson.rutappdto.ReseñaDTO;
import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Component;
import java.awt.Font;
import java.util.List;
import javax.swing.BorderFactory;
import javax.swing.BoxLayout;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JTextArea;
import javax.swing.SwingConstants;

/**
 *
 * @author multaslokas33
 */
public class AgregarReseñas extends javax.swing.JFrame {

    /**
     * Creates new form AgregarReseñas
     */
    private String numeroCamion;

    private JPanel panelPrincipal;
    private JLabel lblTitulo;
    private JComboBox<String> comboEstrellas;
    private JTextArea txtComentario;
    private JButton btnEnviarComentario;
    private JTextArea txtReseñas;

    public AgregarReseñas(String numeroCamion) {
        this.numeroCamion = numeroCamion;
        initComponents();
        agregarComponentesManual();
        cargarReseñasExistentes();
    }

    private void btnEnviarComentarioActionPerformed(java.awt.event.ActionEvent evt) {
        try {
            double estrellas = comboEstrellas.getSelectedIndex() + 1;
            String comentario = txtComentario.getText();

            ReseñaDTO reseña = new ReseñaDTO();
            reseña.setNumeroCamion(numeroCamion);
            reseña.setCalificacion(estrellas);
            reseña.setComentario(comentario);

            ControlNegocio.getInstancia().agregarReseña(reseña);
            JOptionPane.showMessageDialog(this, "¡Gracias por tu reseña!");
            cargarReseñasExistentes();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error al enviar reseña: " + e.getMessage());
        }
    }

    private void cargarReseñasExistentes() {
        List<ReseñaDTO> reseñas = ControlNegocio.getInstancia().obtenerReseñasPorCamion(numeroCamion);
        txtReseñas.setText("");
        for (ReseñaDTO r : reseñas) {
            txtReseñas.append("★".repeat((int) r.getCalificacion()) + "\n"
                    + r.getNombreUsuario() + ": " + r.getComentario() + "\n\n");
        }
    }

    private void agregarComponentesManual() {
        JPanel panelContenido = new JPanel();
        panelContenido.setLayout(new BoxLayout(panelContenido, BoxLayout.Y_AXIS));
        panelContenido.setBackground(Color.WHITE);
        panelContenido.setBorder(BorderFactory.createEmptyBorder(15, 20, 15, 20));

        lblTitulo = new JLabel("¿Qué te pareció el camión " + numeroCamion + "?", SwingConstants.CENTER);
        lblTitulo.setFont(new Font("Roboto", Font.BOLD, 18));
        lblTitulo.setAlignmentX(Component.CENTER_ALIGNMENT);

        comboEstrellas = new JComboBox<>(new String[]{"1", "2", "3", "4", "5"});
        comboEstrellas.setAlignmentX(Component.CENTER_ALIGNMENT);

        txtComentario = new JTextArea(3, 20);
        JScrollPane scrollComentario = new JScrollPane(txtComentario);

        btnEnviarComentario = new JButton("Añadir Comentario");
        btnEnviarComentario.setAlignmentX(Component.CENTER_ALIGNMENT);
        btnEnviarComentario.addActionListener(this::btnEnviarComentarioActionPerformed);

        txtReseñas = new JTextArea(10, 30);
        txtReseñas.setEditable(false);
        JScrollPane scrollReseñas = new JScrollPane(txtReseñas);

        panelContenido.add(lblTitulo);
        panelContenido.add(comboEstrellas);
        panelContenido.add(new JLabel("Comentario:"));
        panelContenido.add(scrollComentario);
        panelContenido.add(btnEnviarComentario);
        panelContenido.add(new JLabel("Reseñas existentes:"));
        panelContenido.add(scrollReseñas);

        // 🔽 Agrega el panel manual al layout principal del jPanel1 (centro)
        jPanel1.setLayout(new BorderLayout());
        jPanel1.add(panelContenido, BorderLayout.CENTER);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(255, 201, 98));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 60, Short.MAX_VALUE)
        );

        jPanel3.setBackground(new java.awt.Color(255, 201, 98));

        jLabel1.setFont(new java.awt.Font("Roboto Condensed Medium", 1, 48)); // NOI18N
        jLabel1.setText("RUTAPP");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(193, 193, 193)
                .addComponent(jLabel1)
                .addContainerGap(198, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 350, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    // End of variables declaration//GEN-END:variables
}
