/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Frames;

import Control.ControlNegocio;
import Control.ControlTimer;
import Control.CordinadorPresentacion;
import Ex.CompraBoletoException;
import Interfaces.TemporizadorObserver;
import excepciones.PagoBoletoException;
import fachada.FUsuarioActivo;
import interfaz.IUsuarioActivo;
import itson.rutappdto.BoletoContext;
import itson.rutappdto.DetallesPagoDTO;
import itson.rutappdto.TarjetaCreditoDTO;
import itson.rutappdto.UsuarioDTO;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.text.AbstractDocument;
import utilerias.FechaDocumentFilter;

/**
 *
 * @author mmax2
 */
public class ComprarBoleto extends javax.swing.JFrame implements TemporizadorObserver {

    
    IUsuarioActivo usuarioActivo = new FUsuarioActivo();
    /**
     * Creates new form ComprarViaje
     */
    public ComprarBoleto() {
        //--------------OBSERVADOR----------
        ControlTimer.getInstancia().limpiarObservadores();
        ControlTimer.getInstancia().agregarObservador(this);
        System.out.println("Observador agregado: " + this.hashCode());
        initComponents();
        this.panelTarjeta.setVisible(false);
        setTitle("Pago");
        setLocationRelativeTo(null);

        buttonGroup1.add(botonPagarMonedero);
        buttonGroup1.add(botonPagarTarjeta);
        ((AbstractDocument) campoVencimiento.getDocument()).setDocumentFilter(new FechaDocumentFilter());

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        BackGround = new javax.swing.JPanel();
        Header = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        Footer = new javax.swing.JPanel();
        botonCancelar = new javax.swing.JButton();
        botonPagarMonedero = new javax.swing.JRadioButton();
        botonPagarTarjeta = new javax.swing.JRadioButton();
        panelTarjeta = new javax.swing.JPanel();
        campoNumeroTarjeta = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        campoNombreTitular = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        campoVencimiento = new javax.swing.JTextField();
        campoCVV = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        btnCompraViaje = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        BackGround.setBackground(new java.awt.Color(255, 255, 255));
        BackGround.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Header.setBackground(new java.awt.Color(255, 201, 98));
        Header.setPreferredSize(new java.awt.Dimension(520, 60));

        jLabel1.setFont(new java.awt.Font("Roboto Condensed Medium", 1, 48)); // NOI18N
        jLabel1.setText("RUTAPP");

        javax.swing.GroupLayout HeaderLayout = new javax.swing.GroupLayout(Header);
        Header.setLayout(HeaderLayout);
        HeaderLayout.setHorizontalGroup(
            HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, HeaderLayout.createSequentialGroup()
                .addContainerGap(166, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(164, 164, 164))
        );
        HeaderLayout.setVerticalGroup(
            HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HeaderLayout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        BackGround.add(Header, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 500, -1));

        Footer.setBackground(new java.awt.Color(255, 201, 98));
        Footer.setPreferredSize(new java.awt.Dimension(520, 60));

        botonCancelar.setFont(new java.awt.Font("Helvetica Neue", 0, 24)); // NOI18N
        botonCancelar.setText("Cancelar");
        botonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout FooterLayout = new javax.swing.GroupLayout(Footer);
        Footer.setLayout(FooterLayout);
        FooterLayout.setHorizontalGroup(
            FooterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FooterLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(botonCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(314, Short.MAX_VALUE))
        );
        FooterLayout.setVerticalGroup(
            FooterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FooterLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(botonCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        BackGround.add(Footer, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 490, 500, -1));

        botonPagarMonedero.setText("Usar monedero");
        botonPagarMonedero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonPagarMonederoActionPerformed(evt);
            }
        });
        BackGround.add(botonPagarMonedero, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, -1, -1));

        botonPagarTarjeta.setText("Usar tarjeta");
        botonPagarTarjeta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonPagarTarjetaActionPerformed(evt);
            }
        });
        BackGround.add(botonPagarTarjeta, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, -1, -1));

        panelTarjeta.setBackground(new java.awt.Color(255, 255, 255));
        panelTarjeta.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        campoNumeroTarjeta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoNumeroTarjetaActionPerformed(evt);
            }
        });

        jLabel2.setText("Numero de tarjeta");

        jLabel3.setText("Nombtre titular");

        jLabel4.setText("Vencimiento");

        campoVencimiento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoVencimientoActionPerformed(evt);
            }
        });

        jLabel5.setText("CVV");

        javax.swing.GroupLayout panelTarjetaLayout = new javax.swing.GroupLayout(panelTarjeta);
        panelTarjeta.setLayout(panelTarjetaLayout);
        panelTarjetaLayout.setHorizontalGroup(
            panelTarjetaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTarjetaLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(panelTarjetaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(campoNumeroTarjeta, javax.swing.GroupLayout.PREFERRED_SIZE, 335, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panelTarjetaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelTarjetaLayout.createSequentialGroup()
                            .addGroup(panelTarjetaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(campoVencimiento, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 126, Short.MAX_VALUE))
                            .addGap(83, 83, 83)
                            .addGroup(panelTarjetaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(campoCVV)
                                .addGroup(panelTarjetaLayout.createSequentialGroup()
                                    .addComponent(jLabel5)
                                    .addGap(0, 0, Short.MAX_VALUE))))
                        .addComponent(campoNombreTitular, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 335, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(55, Short.MAX_VALUE))
        );
        panelTarjetaLayout.setVerticalGroup(
            panelTarjetaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTarjetaLayout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(campoNumeroTarjeta, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(campoNombreTitular, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(panelTarjetaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelTarjetaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(campoVencimiento, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(campoCVV, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        BackGround.add(panelTarjeta, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 190, 410, 240));

        btnCompraViaje.setBackground(new java.awt.Color(240, 152, 39));
        btnCompraViaje.setFont(new java.awt.Font("Roboto Condensed Black", 1, 13)); // NOI18N
        btnCompraViaje.setForeground(new java.awt.Color(255, 255, 255));
        btnCompraViaje.setText("COMPRAR");
        btnCompraViaje.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCompraViajeActionPerformed(evt);
            }
        });
        BackGround.add(btnCompraViaje, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 440, 110, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(BackGround, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(BackGround, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonPagarTarjetaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonPagarTarjetaActionPerformed
        this.panelTarjeta.setVisible(true);
    }//GEN-LAST:event_botonPagarTarjetaActionPerformed

    private void botonPagarMonederoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonPagarMonederoActionPerformed
        this.panelTarjeta.setVisible(false);
    }//GEN-LAST:event_botonPagarMonederoActionPerformed

    private void btnCompraViajeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCompraViajeActionPerformed
    DetallesPagoDTO detallesPago;

    if (botonPagarTarjeta.isSelected()) {
        System.out.println("Pago con tarjeta seleccionado.");
        String numeroTarjeta = campoNumeroTarjeta.getText().trim();
        String nombreTitular = campoNombreTitular.getText().trim();
        String vencimiento = campoVencimiento.getText().trim(); 
        String cvv = campoCVV.getText().trim(); 

        if (numeroTarjeta.isEmpty() || nombreTitular.isEmpty() || vencimiento.isEmpty() || cvv.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this, "Por favor, completa todos los campos de la tarjeta.", "Campos vacíos", javax.swing.JOptionPane.WARNING_MESSAGE);
            return;
        }

        if (!numeroTarjeta.matches("\\d{16}")) {
            javax.swing.JOptionPane.showMessageDialog(this, "El número de tarjeta debe tener 16 dígitos numéricos.", "Número de tarjeta inválido", javax.swing.JOptionPane.ERROR_MESSAGE);
            return;
        }

        if (!cvv.matches("\\d{3}")) {
            javax.swing.JOptionPane.showMessageDialog(this, "El CVV debe tener 3 dígitos numéricos.", "CVV inválido", javax.swing.JOptionPane.ERROR_MESSAGE);
            return;
        }

        // Crear el objeto de tarjeta
        TarjetaCreditoDTO tarjeta = new TarjetaCreditoDTO(numeroTarjeta, nombreTitular, vencimiento, cvv);

        // Crear el DetallesPagoDTO para tarjeta
        detallesPago = new DetallesPagoDTO("Tarjeta", 200.0, BoletoContext.getBoleto(), tarjeta);  // Asignar detallesTarjeta
        
        
    } else if (botonPagarMonedero.isSelected()) {
        // Crear DetallesPagoDTO para pago con monedero sin detalles de tarjeta
        detallesPago = new DetallesPagoDTO("Monedero", 200.0, BoletoContext.getBoleto());  // No pasa detallesTarjeta
        javax.swing.JOptionPane.showMessageDialog(this, "¡Pago con monedero procesado con éxito!");
//        CordinadorPresentacion.getInstancia().abrirResumenCompra(); // Navegar al resumen
//        this.dispose(); // Cerrar la ventana después de la selección del pago
    } else {
        javax.swing.JOptionPane.showMessageDialog(this, "Por favor, selecciona un método de pago.", "Método de pago no seleccionado", javax.swing.JOptionPane.WARNING_MESSAGE);
        return; // Salir si no se seleccionó un método de pago
    }

    // Ahora llamamos al método de negocio para procesar la compra
    boolean compraExitosa = false;
    try {
        System.out.println("DEBUGPRESENTACION");
        compraExitosa = ControlNegocio.getInstancia().comprarBoleto(detallesPago, usuarioActivo.obtenerUsuarioActual());
    } catch (PagoBoletoException ex) {
        Logger.getLogger(ComprarBoleto.class.getName()).log(Level.SEVERE, "Error al procesar el pago: ", ex);
        javax.swing.JOptionPane.showMessageDialog(this, "Error en el procesamiento del pago. Por favor, intente nuevamente.", "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
    } catch (CompraBoletoException ex) {
        Logger.getLogger(ComprarBoleto.class.getName()).log(Level.SEVERE, "Error en la compra del boleto: ", ex);
        javax.swing.JOptionPane.showMessageDialog(this, "Error en la compra del boleto. Por favor, intente nuevamente.", "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
    }

    // Lógica adicional si la compra fue exitosa
    if (compraExitosa) {
        javax.swing.JOptionPane.showMessageDialog(this, "¡Compra realizada con éxito!");
        CordinadorPresentacion.getInstancia().abrirPantallaPrincipal(); // Regresar a la pantalla principal
    }
    this.dispose(); // Cerrar la ventana después de pasar los datos
    }//GEN-LAST:event_btnCompraViajeActionPerformed

    private void campoNumeroTarjetaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoNumeroTarjetaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoNumeroTarjetaActionPerformed

    private void campoVencimientoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoVencimientoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoVencimientoActionPerformed

    private void botonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCancelarActionPerformed
        int confirmacion = JOptionPane.showConfirmDialog(null, "Confirmar cancelación", "¿Estas seguro de cancelar"
                + "la operacion? Se borrará tu progreso", JOptionPane.YES_NO_OPTION);

        if (confirmacion == JOptionPane.YES_OPTION) {
            BoletoContext.limpiarBoleto();
            JOptionPane.showMessageDialog(null, "Has cancelado el proceso.\n Regresaras a la pantalla principal");
            CordinadorPresentacion.getInstancia().abrirPantallaPrincipal();
            this.dispose();
            //AQUI DEBERIA DE IR ALGO PARA REGRESAR LOS ASIENTOS A DISPONIBLES
        }
    }//GEN-LAST:event_botonCancelarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel BackGround;
    private javax.swing.JPanel Footer;
    private javax.swing.JPanel Header;
    private javax.swing.JButton botonCancelar;
    private javax.swing.JRadioButton botonPagarMonedero;
    private javax.swing.JRadioButton botonPagarTarjeta;
    private javax.swing.JButton btnCompraViaje;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JTextField campoCVV;
    private javax.swing.JTextField campoNombreTitular;
    private javax.swing.JTextField campoNumeroTarjeta;
    private javax.swing.JTextField campoVencimiento;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel panelTarjeta;
    // End of variables declaration//GEN-END:variables

    @Override
    public void tiempoAgotado() {
        JOptionPane.showMessageDialog(this, "El tiempo se agotó. Serás redirigido al menú principal.");
        this.dispose(); // Cierra esta pantalla
        new MainMenu().setVisible(true); // Abre la pantalla principal
    }
}
