/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Frames;

import Control.ControlNegocio;
import Control.CordinadorPresentacion;
import itson.rutappbo.IUsuariosBO;
import itson.rutappbo.implementaciones.UsuariosBO;
import itson.rutappdto.UsuarioDTO;
import java.awt.Color;

/**
 *
 * @author mmax2
 */
public class InicioSesion extends javax.swing.JFrame {

    IUsuariosBO usuariosBO;

    private javax.swing.JLabel lblMensaje;

    /**
     * Creates new form ComprarViaje
     */
    public InicioSesion() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setTitle("Rutapp");
        //LABEL
        lblMensaje = new javax.swing.JLabel();
        lblMensaje.setForeground(java.awt.Color.RED);
        lblMensaje.setText("");
        BackGround.add(lblMensaje, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 450, 320, 20));

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BackGround = new javax.swing.JPanel();
        Header = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        Footer = new javax.swing.JPanel();
        usuarioTxt = new javax.swing.JTextField();
        usuarioLbl = new javax.swing.JLabel();
        contraseniaLbl1 = new javax.swing.JLabel();
        contraseniaTxt = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        IniciarSesionBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        BackGround.setBackground(new java.awt.Color(255, 255, 255));
        BackGround.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Header.setBackground(new java.awt.Color(255, 201, 98));
        Header.setPreferredSize(new java.awt.Dimension(520, 60));

        jLabel1.setFont(new java.awt.Font("Roboto Condensed Medium", 1, 48)); // NOI18N
        jLabel1.setText("RUTAPP");

        javax.swing.GroupLayout HeaderLayout = new javax.swing.GroupLayout(Header);
        Header.setLayout(HeaderLayout);
        HeaderLayout.setHorizontalGroup(
            HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, HeaderLayout.createSequentialGroup()
                .addContainerGap(166, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(164, 164, 164))
        );
        HeaderLayout.setVerticalGroup(
            HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HeaderLayout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        BackGround.add(Header, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 500, -1));

        Footer.setBackground(new java.awt.Color(255, 201, 98));
        Footer.setPreferredSize(new java.awt.Dimension(520, 60));

        javax.swing.GroupLayout FooterLayout = new javax.swing.GroupLayout(Footer);
        Footer.setLayout(FooterLayout);
        FooterLayout.setHorizontalGroup(
            FooterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 500, Short.MAX_VALUE)
        );
        FooterLayout.setVerticalGroup(
            FooterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 60, Short.MAX_VALUE)
        );

        BackGround.add(Footer, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 490, 500, -1));

        usuarioTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usuarioTxtActionPerformed(evt);
            }
        });
        BackGround.add(usuarioTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 230, 300, 30));

        usuarioLbl.setText("Usuario");
        BackGround.add(usuarioLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 210, 130, -1));

        contraseniaLbl1.setText("Contraseña");
        BackGround.add(contraseniaLbl1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 280, -1, -1));

        contraseniaTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                contraseniaTxtActionPerformed(evt);
            }
        });
        BackGround.add(contraseniaTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 300, 300, 30));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/busPng.png"))); // NOI18N
        BackGround.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 80, 210, 120));

        IniciarSesionBtn.setBackground(new java.awt.Color(255, 201, 98));
        IniciarSesionBtn.setForeground(new java.awt.Color(0, 0, 0));
        IniciarSesionBtn.setText("Iniciar Sesion");
        IniciarSesionBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IniciarSesionBtnActionPerformed(evt);
            }
        });
        BackGround.add(IniciarSesionBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 380, 130, 60));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(BackGround, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(BackGround, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void contraseniaTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_contraseniaTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_contraseniaTxtActionPerformed

    private void usuarioTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usuarioTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usuarioTxtActionPerformed

    private void IniciarSesionBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IniciarSesionBtnActionPerformed
        String numero = usuarioTxt.getText().trim();
        String pass = contraseniaTxt.getText().trim();
        UsuarioDTO usuarioPresentacion = new UsuarioDTO(numero, pass);
        // Usamos la fachada para acceder a la interfaz de usuario activo
        IUsuariosBO usuariosBO = new UsuariosBO(); // Para validar las credenciales en la base de datos

        // Verificamos si las credenciales son correctas
        String resultado = usuariosBO.login(usuarioPresentacion);
        lblMensaje.setText(resultado);

        if (resultado.equals("Inicio de sesión exitoso.")) {
            lblMensaje.setForeground(new Color(0, 128, 0)); // Verde

            // Ahora, a través de la fachada, obtenemos el usuario autenticado
            UsuarioDTO usuario = usuarioActivoManager.UsuarioActivoManager.getInstancia().getUsuario();

            // Llamamos al controlador de negocio para iniciar la sesión
            // Llama a la capa de negocio para gestionar la sesión
            ControlNegocio.getInstancia().iniciarSesion(usuario);

            // Redirigimos a la pantalla principal
            CordinadorPresentacion.getInstancia().abrirPantallaPrincipal();
            this.dispose();  // Cierra la ventana de inicio de sesión
        } else {
            lblMensaje.setForeground(Color.RED);  // Rojo si es error
        }

    }//GEN-LAST:event_IniciarSesionBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel BackGround;
    private javax.swing.JPanel Footer;
    private javax.swing.JPanel Header;
    private javax.swing.JButton IniciarSesionBtn;
    private javax.swing.JLabel contraseniaLbl1;
    private javax.swing.JTextField contraseniaTxt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel usuarioLbl;
    private javax.swing.JTextField usuarioTxt;
    // End of variables declaration//GEN-END:variables
}
