/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Frames;

import java.awt.Color;

/**
 *
 * @author mmax2
 */
public class InicioSesion extends javax.swing.JFrame {

    /**
     * Creates new form ComprarViaje
     */
    public InicioSesion() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setTitle("Rutapp");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BackGround = new javax.swing.JPanel();
        Header = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        Footer = new javax.swing.JPanel();
        usuarioTxt = new javax.swing.JTextField();
        usuarioLbl = new javax.swing.JLabel();
        contraseniaLbl1 = new javax.swing.JLabel();
        usuarioTxt1 = new javax.swing.JTextField();
        pnlBotonIniciar = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        BackGround.setBackground(new java.awt.Color(255, 255, 255));
        BackGround.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Header.setBackground(new java.awt.Color(255, 201, 98));
        Header.setPreferredSize(new java.awt.Dimension(520, 60));

        jLabel1.setFont(new java.awt.Font("Roboto Condensed Medium", 1, 48)); // NOI18N
        jLabel1.setText("RUTAPP");

        javax.swing.GroupLayout HeaderLayout = new javax.swing.GroupLayout(Header);
        Header.setLayout(HeaderLayout);
        HeaderLayout.setHorizontalGroup(
            HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, HeaderLayout.createSequentialGroup()
                .addContainerGap(166, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(164, 164, 164))
        );
        HeaderLayout.setVerticalGroup(
            HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HeaderLayout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        BackGround.add(Header, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 500, -1));

        Footer.setBackground(new java.awt.Color(255, 201, 98));
        Footer.setPreferredSize(new java.awt.Dimension(520, 60));

        javax.swing.GroupLayout FooterLayout = new javax.swing.GroupLayout(Footer);
        Footer.setLayout(FooterLayout);
        FooterLayout.setHorizontalGroup(
            FooterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 500, Short.MAX_VALUE)
        );
        FooterLayout.setVerticalGroup(
            FooterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 60, Short.MAX_VALUE)
        );

        BackGround.add(Footer, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 490, 500, -1));
        BackGround.add(usuarioTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 230, 300, 30));

        usuarioLbl.setText("Usuario");
        BackGround.add(usuarioLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 210, 130, -1));

        contraseniaLbl1.setText("Contraseña");
        BackGround.add(contraseniaLbl1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 280, -1, -1));
        BackGround.add(usuarioTxt1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 300, 300, 30));

        pnlBotonIniciar.setBackground(new java.awt.Color(255, 201, 98));
        pnlBotonIniciar.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        pnlBotonIniciar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        pnlBotonIniciar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pnlBotonIniciarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pnlBotonIniciarMouseExited(evt);
            }
        });

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Iniciar Sesion");

        javax.swing.GroupLayout pnlBotonIniciarLayout = new javax.swing.GroupLayout(pnlBotonIniciar);
        pnlBotonIniciar.setLayout(pnlBotonIniciarLayout);
        pnlBotonIniciarLayout.setHorizontalGroup(
            pnlBotonIniciarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBotonIniciarLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );
        pnlBotonIniciarLayout.setVerticalGroup(
            pnlBotonIniciarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBotonIniciarLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel3)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        BackGround.add(pnlBotonIniciar, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 360, 140, 50));

        jLabel4.setIcon(new javax.swing.ImageIcon("/Users/juanpheras/ITSON/ISW/4to Semestre/DiseñoSoftware/trabajoDiseño/DisenoSoftwareProyecto/PresentacionRutApp/src/main/resources/imagenes/busPng.png")); // NOI18N
        BackGround.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 80, 210, 120));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(BackGround, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(BackGround, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void pnlBotonIniciarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlBotonIniciarMouseEntered
        pnlBotonIniciar.setBackground(new Color(232, 159, 19));
    }//GEN-LAST:event_pnlBotonIniciarMouseEntered

    private void pnlBotonIniciarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlBotonIniciarMouseExited
        pnlBotonIniciar.setBackground(new Color(255, 201, 98));
    }//GEN-LAST:event_pnlBotonIniciarMouseExited

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel BackGround;
    private javax.swing.JPanel Footer;
    private javax.swing.JPanel Header;
    private javax.swing.JLabel contraseniaLbl1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel pnlBotonIniciar;
    private javax.swing.JLabel usuarioLbl;
    private javax.swing.JTextField usuarioTxt;
    private javax.swing.JTextField usuarioTxt1;
    // End of variables declaration//GEN-END:variables
}
