/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Frames;

import Control.ControlNegocio;
import itson.rutappdto.AsientoBoletoDTO;
import itson.rutappdto.CompraDTO;
import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Cursor;
import java.awt.Dimension;
import java.awt.Font;
import java.awt.GridLayout;
import java.text.SimpleDateFormat;
import java.util.List;
import javax.swing.BorderFactory;
import javax.swing.Box;
import javax.swing.BoxLayout;
import javax.swing.DefaultListModel;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.SwingConstants;
import usuarioActivoManager.UsuarioActivoManager;

/**
 *
 * @author multaslokas33
 */
public class MisBoletos extends javax.swing.JFrame {

    private JPanel panelContenido;

    public MisBoletos() {
        setTitle("Mis Boletos");
        setSize(600, 500);
        setLocationRelativeTo(null);
        setDefaultCloseOperation(DISPOSE_ON_CLOSE);

        panelContenido = new JPanel();
        panelContenido.setLayout(new BoxLayout(panelContenido, BoxLayout.Y_AXIS));
        panelContenido.setBackground(Color.WHITE);

        JScrollPane scrollPane = new JScrollPane(panelContenido);
        scrollPane.getVerticalScrollBar().setUnitIncrement(16);
        add(scrollPane);

        cargarBoletos();
    }

    private void cargarBoletos() {
        List<CompraDTO> compras = ControlNegocio.getInstancia()
                .obtenerComprasUsuario(UsuarioActivoManager.getInstancia().getUsuario());

        if (compras.isEmpty()) {
            JLabel sinBoletos = new JLabel("No tienes boletos comprados.", SwingConstants.CENTER);
            sinBoletos.setFont(new Font("SansSerif", Font.PLAIN, 16));
            panelContenido.add(sinBoletos);
            return;
        }

        for (CompraDTO compra : compras) {
            JPanel panel = crearPanelCompra(compra);
            panelContenido.add(panel);
            panelContenido.add(Box.createVerticalStrut(15));
        }
    }

    private JPanel crearPanelCompra(CompraDTO compra) {
        JPanel panel = new JPanel(new BorderLayout());
        panel.setBorder(BorderFactory.createLineBorder(Color.GRAY, 2));
        panel.setBackground(new Color(240, 248, 255));
        panel.setPreferredSize(new Dimension(550, 130));
        panel.setMaximumSize(new Dimension(550, 130));

        Color baseColor = panel.getBackground();
        Color hoverColor = new Color(210, 230, 255);

        panel.addMouseListener(new java.awt.event.MouseAdapter() {
            @Override
            public void mouseEntered(java.awt.event.MouseEvent e) {
                panel.setBackground(hoverColor);
                panel.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
            }

            public void mouseExited(java.awt.event.MouseEvent e) {
                panel.setBackground(baseColor);
                panel.setCursor(Cursor.getDefaultCursor());
            }
        });
        
        JLabel titulo = new JLabel(compra.getOrigen() + " ➡ " + compra.getDestino(), SwingConstants.CENTER);
        titulo.setFont(new Font("SansSerif", Font.BOLD, 16));
        panel.add(titulo, BorderLayout.NORTH);

        JPanel detalles = new JPanel(new GridLayout(2, 2));
        detalles.setOpaque(false);

        SimpleDateFormat fFecha = new SimpleDateFormat("yyyy-MM-dd");

        detalles.add(new JLabel("Fecha: " + fFecha.format(compra.getFecha())));
        detalles.add(new JLabel("Hora: " + compra.getHrSalida()));
        detalles.add(new JLabel("Camión: " + compra.getCamion().getNumeroCamion()));
        detalles.add(new JLabel("Precio: $" + compra.getPrecio()));

        panel.add(detalles, BorderLayout.CENTER);

        StringBuilder asientosTexto = new StringBuilder("Asientos: ");
        for (AsientoBoletoDTO ab : compra.getListaAsiento()) {
            asientosTexto.append(ab.getAsiento().getNumero()).append(" ");
        }

        JLabel asientos = new JLabel(asientosTexto.toString());
        asientos.setHorizontalAlignment(SwingConstants.CENTER);
        panel.add(asientos, BorderLayout.SOUTH);

        return panel;
    }

        /**
         * This method is called from within the constructor to initialize the
         * form. WARNING: Do NOT modify this code. The content of this method is
         * always regenerated by the Form Editor.
         */
        @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        listaBoletos = new javax.swing.JList<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        listaBoletos.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(listaBoletos);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(69, 69, 69)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 401, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(60, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(78, 78, 78)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(60, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList<String> listaBoletos;
    // End of variables declaration//GEN-END:variables
}
