/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Frames;

import Control.ControlNegocio;
import itson.rutappdto.CompraDTO;
import itson.rutappdto.UsuarioDTO;
import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Component;
import java.awt.FlowLayout;
import java.util.HashSet;
import java.util.List;
import java.util.Set;
import javax.swing.BorderFactory;
import javax.swing.BoxLayout;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JScrollPane;

/**
 *
 * @author multaslokas33
 */
public class Reseñas extends javax.swing.JFrame {

    private JPanel panelCamiones;

    /**
     * Creates new form Reseñas
     */
    public Reseñas() {
        initComponents(); // se mantiene
        personalizarComponentes();
        cargarCamionesConCompras();
    }

    private void cargarCamionesConCompras() {
        UsuarioDTO usuario = ControlNegocio.getInstancia().obtenerUsuarioActivo();
        List<CompraDTO> compras = ControlNegocio.getInstancia().obtenerComprasUsuario(usuario);

        Set<String> camionesUnicos = new HashSet<>();
        for (CompraDTO compra : compras) {
            String numCamion = compra.getViaje().getCamion().getNumeroCamion();
            camionesUnicos.add(numCamion);
        }

        if (camionesUnicos.isEmpty()) {
            JLabel lbl = new JLabel("No tienes camiones para reseñar.");
            lbl.setAlignmentX(Component.CENTER_ALIGNMENT);
            panelCamiones.add(lbl);
        } else {
            for (String camion : camionesUnicos) {
                JPanel panelItem = new JPanel(new FlowLayout(FlowLayout.LEFT));
                panelItem.setBackground(Color.WHITE);

                JLabel lblCamion = new JLabel("Autobús " + camion);
                JButton btn = new JButton("Reseñar");

                btn.addActionListener(e -> {
                    new AgregarReseñas(camion).setVisible(true);
                    dispose(); // opcional, cerrar esta ventana
                });

                panelItem.add(lblCamion);
                panelItem.add(btn);
                panelCamiones.add(panelItem);
            }
        }

        panelCamiones.revalidate();
        panelCamiones.repaint();
    }

    private void personalizarComponentes() {
        panelCamiones = new JPanel();
        panelCamiones.setLayout(new BoxLayout(panelCamiones, BoxLayout.Y_AXIS));
        panelCamiones.setBackground(Color.WHITE);
        panelCamiones.setBorder(BorderFactory.createEmptyBorder(10, 20, 10, 20));

        JScrollPane scroll = new JScrollPane(panelCamiones);
        scroll.setVerticalScrollBarPolicy(JScrollPane.VERTICAL_SCROLLBAR_ALWAYS);
        scroll.getVerticalScrollBar().setUnitIncrement(16);

        // Asegúrate de que tu JFrame tenga BorderLayout
        this.getContentPane().setLayout(new BorderLayout());
        this.getContentPane().add(scroll, BorderLayout.CENTER);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
