/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Frames;

import enumm.estadoAsiento;
import itson.rutappdto.AsientoBoletoDTO;
import itson.rutappdto.AsientoDTO;
import itson.rutappdto.BoletoDTO;
import itson.rutappdto.CamionDTO;
import itson.rutappdto.DetallesPagoDTO;
import itson.rutappdto.UsuarioDTO;
import java.awt.BorderLayout;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JFrame;
import javax.swing.JScrollPane;
import javax.swing.JTextArea;

/**
 *
 * @author mmax2
 */
public class ResumenCompra extends javax.swing.JFrame {

    private final JTextArea resumenTextArea;

    private List<AsientosDisponibles.AsientoAsignado> asientosAsignados;

    /**
     * Creates new form ComprarViaje
     */
    public ResumenCompra() {
        initComponents();
        setTitle("Resumen de Compra");
        setSize(400, 300);
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        setLocationRelativeTo(null);

        resumenTextArea = new JTextArea();
        resumenTextArea.setEditable(false);
        add(new JScrollPane(resumenTextArea), BorderLayout.CENTER);;

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator6 = new javax.swing.JSeparator();
        BackGround = new javax.swing.JPanel();
        Header = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        Footer = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        lblOrigen = new javax.swing.JLabel();
        lblDestino = new javax.swing.JLabel();
        lblAsientos = new javax.swing.JLabel();
        lblDuracion = new javax.swing.JLabel();
        lblNombres = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        jSeparator7 = new javax.swing.JSeparator();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        lblPrecio = new javax.swing.JLabel();
        lblTotal = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        lblMonedero = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        BackGround.setBackground(new java.awt.Color(255, 255, 255));
        BackGround.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                BackGroundInputMethodTextChanged(evt);
            }
        });
        BackGround.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Header.setBackground(new java.awt.Color(255, 201, 98));
        Header.setPreferredSize(new java.awt.Dimension(520, 60));

        jLabel1.setFont(new java.awt.Font("Roboto Condensed Medium", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("RUTAPP");

        javax.swing.GroupLayout HeaderLayout = new javax.swing.GroupLayout(Header);
        Header.setLayout(HeaderLayout);
        HeaderLayout.setHorizontalGroup(
            HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, HeaderLayout.createSequentialGroup()
                .addContainerGap(166, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(164, 164, 164))
        );
        HeaderLayout.setVerticalGroup(
            HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HeaderLayout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        BackGround.add(Header, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 500, -1));

        Footer.setBackground(new java.awt.Color(255, 201, 98));
        Footer.setPreferredSize(new java.awt.Dimension(520, 60));

        javax.swing.GroupLayout FooterLayout = new javax.swing.GroupLayout(Footer);
        Footer.setLayout(FooterLayout);
        FooterLayout.setHorizontalGroup(
            FooterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 500, Short.MAX_VALUE)
        );
        FooterLayout.setVerticalGroup(
            FooterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 60, Short.MAX_VALUE)
        );

        BackGround.add(Footer, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 530, 500, 60));

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Serif", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Total");
        BackGround.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 440, 160, -1));
        BackGround.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 173, 480, 0));
        BackGround.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 270, -1, 110));

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Serif", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Resumen de compra");
        BackGround.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, 160, -1));

        lblOrigen.setBackground(new java.awt.Color(255, 255, 255));
        lblOrigen.setFont(new java.awt.Font("Serif", 0, 18)); // NOI18N
        lblOrigen.setForeground(new java.awt.Color(0, 0, 0));
        lblOrigen.setText("Origen");
        lblOrigen.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                lblOrigenInputMethodTextChanged(evt);
            }
        });
        BackGround.add(lblOrigen, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 150, 70, 20));

        lblDestino.setBackground(new java.awt.Color(255, 255, 255));
        lblDestino.setFont(new java.awt.Font("Serif", 0, 18)); // NOI18N
        lblDestino.setForeground(new java.awt.Color(0, 0, 0));
        lblDestino.setText("Destino");
        BackGround.add(lblDestino, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 190, 160, -1));

        lblAsientos.setBackground(new java.awt.Color(255, 255, 255));
        lblAsientos.setFont(new java.awt.Font("Serif", 0, 18)); // NOI18N
        lblAsientos.setForeground(new java.awt.Color(0, 0, 0));
        lblAsientos.setText("Asiento(s)");
        BackGround.add(lblAsientos, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 230, 160, -1));

        lblDuracion.setBackground(new java.awt.Color(255, 255, 255));
        lblDuracion.setFont(new java.awt.Font("Serif", 0, 18)); // NOI18N
        lblDuracion.setForeground(new java.awt.Color(0, 0, 0));
        lblDuracion.setText("00:00");
        BackGround.add(lblDuracion, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 270, 160, -1));

        lblNombres.setBackground(new java.awt.Color(255, 255, 255));
        lblNombres.setFont(new java.awt.Font("Serif", 0, 18)); // NOI18N
        lblNombres.setForeground(new java.awt.Color(0, 0, 0));
        lblNombres.setText("Nombre(s)");
        BackGround.add(lblNombres, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 310, 160, -1));

        jLabel9.setBackground(new java.awt.Color(255, 255, 255));
        jLabel9.setFont(new java.awt.Font("Serif", 0, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 0));
        jLabel9.setText("Precio");
        BackGround.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 360, 160, -1));

        jLabel10.setBackground(new java.awt.Color(255, 255, 255));
        jLabel10.setFont(new java.awt.Font("Serif", 0, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 0, 0));
        jLabel10.setText("Monedero");
        BackGround.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 400, 160, -1));
        BackGround.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 460, -1));
        BackGround.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 340, 440, 20));
        BackGround.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 463, 460, 0));
        BackGround.add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 510, 460, 10));

        jLabel11.setBackground(new java.awt.Color(255, 255, 255));
        jLabel11.setFont(new java.awt.Font("Serif", 0, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 0, 0));
        jLabel11.setText("Origen");
        BackGround.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 150, 160, -1));

        jLabel12.setBackground(new java.awt.Color(255, 255, 255));
        jLabel12.setFont(new java.awt.Font("Serif", 0, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 0, 0));
        jLabel12.setText("Destino");
        BackGround.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 190, 160, -1));

        jLabel13.setBackground(new java.awt.Color(255, 255, 255));
        jLabel13.setFont(new java.awt.Font("Serif", 0, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(0, 0, 0));
        jLabel13.setText("Asiento(s)");
        BackGround.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 230, 160, -1));

        lblPrecio.setBackground(new java.awt.Color(255, 255, 255));
        lblPrecio.setFont(new java.awt.Font("Serif", 0, 18)); // NOI18N
        lblPrecio.setForeground(new java.awt.Color(0, 0, 0));
        lblPrecio.setText("$....");
        BackGround.add(lblPrecio, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 360, 160, -1));

        lblTotal.setBackground(new java.awt.Color(255, 255, 255));
        lblTotal.setFont(new java.awt.Font("Serif", 0, 18)); // NOI18N
        lblTotal.setForeground(new java.awt.Color(0, 0, 0));
        lblTotal.setText("$....");
        BackGround.add(lblTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 440, 160, -1));

        jLabel15.setBackground(new java.awt.Color(255, 255, 255));
        jLabel15.setFont(new java.awt.Font("Serif", 0, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(0, 0, 0));
        jLabel15.setText("Duracion");
        BackGround.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 270, 160, -1));

        jLabel16.setBackground(new java.awt.Color(255, 255, 255));
        jLabel16.setFont(new java.awt.Font("Serif", 0, 18)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(0, 0, 0));
        jLabel16.setText("Nombre(s)");
        BackGround.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 310, 160, -1));

        lblMonedero.setBackground(new java.awt.Color(255, 255, 255));
        lblMonedero.setFont(new java.awt.Font("Serif", 0, 18)); // NOI18N
        lblMonedero.setForeground(new java.awt.Color(0, 0, 0));
        lblMonedero.setText("$....");
        BackGround.add(lblMonedero, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 400, 160, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(BackGround, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(BackGround, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lblOrigenInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_lblOrigenInputMethodTextChanged

    }//GEN-LAST:event_lblOrigenInputMethodTextChanged

    private void BackGroundInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_BackGroundInputMethodTextChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_BackGroundInputMethodTextChanged

    private void datosResumen(BoletoDTO boleto) {

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ResumenCompra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ResumenCompra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ResumenCompra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ResumenCompra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ResumenCompra().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel BackGround;
    private javax.swing.JPanel Footer;
    private javax.swing.JPanel Header;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JLabel lblAsientos;
    private javax.swing.JLabel lblDestino;
    private javax.swing.JLabel lblDuracion;
    private javax.swing.JLabel lblMonedero;
    private javax.swing.JLabel lblNombres;
    private javax.swing.JLabel lblOrigen;
    private javax.swing.JLabel lblPrecio;
    private javax.swing.JLabel lblTotal;
    // End of variables declaration//GEN-END:variables
    public void mostrarResumen(List<AsientosDisponibles.AsientoAsignado> lista, BoletoDTO camion, double monedero) {
        // Origen y destino
        lblOrigen.setText(camion.getOrigen());
        lblDestino.setText(camion.getDestino());

        // Duración (puedes ajustarlo según tus datos)
        lblDuracion.setText(camion.getDuracion());

        // Asientos y nombres
        StringBuilder asientos = new StringBuilder();
        StringBuilder nombres = new StringBuilder();

        for (AsientosDisponibles.AsientoAsignado asignado : lista) {
            asientos.append(asignado.getNumeroAsiento()).append(" ");
            nombres.append(asignado.getNombrePasajero()).append(" / ");
        }

        lblAsientos.setText(asientos.toString().trim());
        lblNombres.setText(nombres.toString().trim());

        // Precio por asiento
        double precio = camion.getPrecio();
        double total = precio * lista.size();

        lblPrecio.setText("$" + precio);
        lblMonedero.setText("$" + monedero);
        lblTotal.setText("$" + total);
    }
}
