/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Frames;

import Control.ControlNegocio;
import Control.CordinadorPresentacion;
import enumm.estadoAsiento;
import itson.rutappdto.AsientoAsignadoDTO;
import itson.rutappdto.AsientoBoletoDTO;
import itson.rutappdto.AsientoDTO;
import itson.rutappdto.BoletoContext;
import itson.rutappdto.BoletoDTO;
import itson.rutappdto.CamionDTO;
import itson.rutappdto.DetallesPagoDTO;
import itson.rutappdto.UsuarioDTO;
import java.awt.BorderLayout;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JScrollPane;
import javax.swing.JTextArea;

/**
 *
 * @author mmax2
 */
public class ResumenCompra extends javax.swing.JFrame {

    private final JTextArea resumenTextArea;
    CamionDTO camion;

    UsuarioDTO usuario = new UsuarioDTO("Juan Pérez");

    List<AsientoDTO> asientosCamion = new ArrayList<>();
    List<AsientoBoletoDTO> asientosBoleto = new ArrayList<>();

//    private List<AsientosDisponibles.AsientoAsignado> asientosAsignados;
    /**
     * Creates new form ComprarViaje
     */
    public ResumenCompra() {
        initComponents();
        setTitle("Resumen de Compra");
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        setLocationRelativeTo(null);

        resumenTextArea = new JTextArea();
        resumenTextArea.setEditable(false);
        add(new JScrollPane(resumenTextArea), BorderLayout.CENTER);

        ControlNegocio control = ControlNegocio.getInstancia();

        BoletoDTO boleto = new BoletoDTO(
                control.getOrigenSeleccionado(),
                control.getDestinoSeleccionado(),
                control.getPrecioSeleccionado(),
                control.getDuracionSeleccionada(),
                control.getCamionSeleccionado(),
                control.getAsientosSeleccionados()
        );

        mostrarResumen(BoletoContext.getBoleto());

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator6 = new javax.swing.JSeparator();
        BackGround = new javax.swing.JPanel();
        Header = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        Footer = new javax.swing.JPanel();
        botonCancelar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        lblOrigen = new javax.swing.JLabel();
        lblDestino = new javax.swing.JLabel();
        lblAsientos = new javax.swing.JLabel();
        lblDuracion = new javax.swing.JLabel();
        lblNombres = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        jSeparator7 = new javax.swing.JSeparator();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        lblPrecio = new javax.swing.JLabel();
        lblTotal = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        botonAceptar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        BackGround.setBackground(new java.awt.Color(255, 255, 255));
        BackGround.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                BackGroundInputMethodTextChanged(evt);
            }
        });
        BackGround.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Header.setBackground(new java.awt.Color(255, 201, 98));
        Header.setPreferredSize(new java.awt.Dimension(520, 60));

        jLabel1.setFont(new java.awt.Font("Roboto Condensed Medium", 1, 48)); // NOI18N
        jLabel1.setText("RUTAPP");

        javax.swing.GroupLayout HeaderLayout = new javax.swing.GroupLayout(Header);
        Header.setLayout(HeaderLayout);
        HeaderLayout.setHorizontalGroup(
            HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, HeaderLayout.createSequentialGroup()
                .addContainerGap(241, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(184, 184, 184))
        );
        HeaderLayout.setVerticalGroup(
            HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, HeaderLayout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        BackGround.add(Header, new org.netbeans.lib.awtextra.AbsoluteConstraints(-50, 0, 620, -1));

        Footer.setBackground(new java.awt.Color(255, 201, 98));
        Footer.setPreferredSize(new java.awt.Dimension(520, 60));

        botonCancelar.setFont(new java.awt.Font("Helvetica Neue", 0, 24)); // NOI18N
        botonCancelar.setText("Cancelar");
        botonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout FooterLayout = new javax.swing.GroupLayout(Footer);
        Footer.setLayout(FooterLayout);
        FooterLayout.setHorizontalGroup(
            FooterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FooterLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(botonCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(484, Short.MAX_VALUE))
        );
        FooterLayout.setVerticalGroup(
            FooterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FooterLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(botonCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        BackGround.add(Footer, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 530, 670, 60));

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Serif", 0, 18)); // NOI18N
        jLabel2.setText("Total");
        BackGround.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 420, 160, -1));
        BackGround.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 173, 480, 0));
        BackGround.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 270, -1, 110));

        lblOrigen.setBackground(new java.awt.Color(255, 255, 255));
        lblOrigen.setFont(new java.awt.Font("Serif", 0, 18)); // NOI18N
        lblOrigen.setText("Origen");
        lblOrigen.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                lblOrigenInputMethodTextChanged(evt);
            }
        });
        BackGround.add(lblOrigen, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 130, 150, 20));

        lblDestino.setBackground(new java.awt.Color(255, 255, 255));
        lblDestino.setFont(new java.awt.Font("Serif", 0, 18)); // NOI18N
        lblDestino.setText("Destino");
        BackGround.add(lblDestino, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 170, 160, -1));

        lblAsientos.setBackground(new java.awt.Color(255, 255, 255));
        lblAsientos.setFont(new java.awt.Font("Serif", 0, 18)); // NOI18N
        lblAsientos.setText("Asiento(s)");
        BackGround.add(lblAsientos, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 210, 160, -1));

        lblDuracion.setBackground(new java.awt.Color(255, 255, 255));
        lblDuracion.setFont(new java.awt.Font("Serif", 0, 18)); // NOI18N
        lblDuracion.setText("00:00");
        BackGround.add(lblDuracion, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 250, 160, -1));

        lblNombres.setBackground(new java.awt.Color(255, 255, 255));
        lblNombres.setFont(new java.awt.Font("Serif", 0, 18)); // NOI18N
        lblNombres.setText("Nombre(s)");
        BackGround.add(lblNombres, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 290, 250, -1));

        jLabel9.setBackground(new java.awt.Color(255, 255, 255));
        jLabel9.setFont(new java.awt.Font("Serif", 0, 18)); // NOI18N
        jLabel9.setText("Precio");
        BackGround.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 340, 160, -1));
        BackGround.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 112, 530, 20));
        BackGround.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 330, 530, 20));
        BackGround.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 463, 460, 0));
        BackGround.add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 460, 530, 10));

        jLabel11.setBackground(new java.awt.Color(255, 255, 255));
        jLabel11.setFont(new java.awt.Font("Serif", 0, 18)); // NOI18N
        jLabel11.setText("Origen");
        BackGround.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 160, -1));

        jLabel12.setBackground(new java.awt.Color(255, 255, 255));
        jLabel12.setFont(new java.awt.Font("Serif", 0, 18)); // NOI18N
        jLabel12.setText("Destino");
        BackGround.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, 160, -1));

        jLabel13.setBackground(new java.awt.Color(255, 255, 255));
        jLabel13.setFont(new java.awt.Font("Serif", 0, 18)); // NOI18N
        jLabel13.setText("Asiento(s)");
        BackGround.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, 160, -1));

        lblPrecio.setBackground(new java.awt.Color(255, 255, 255));
        lblPrecio.setFont(new java.awt.Font("Serif", 0, 18)); // NOI18N
        lblPrecio.setText("$....");
        BackGround.add(lblPrecio, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 340, 160, -1));

        lblTotal.setBackground(new java.awt.Color(255, 255, 255));
        lblTotal.setFont(new java.awt.Font("Serif", 0, 18)); // NOI18N
        lblTotal.setText("$....");
        BackGround.add(lblTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 420, 160, -1));

        jLabel15.setBackground(new java.awt.Color(255, 255, 255));
        jLabel15.setFont(new java.awt.Font("Serif", 0, 18)); // NOI18N
        jLabel15.setText("Duracion");
        BackGround.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, 160, -1));

        jLabel16.setBackground(new java.awt.Color(255, 255, 255));
        jLabel16.setFont(new java.awt.Font("Serif", 0, 18)); // NOI18N
        jLabel16.setText("Nombre(s)");
        BackGround.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 290, 160, -1));

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Serif", 0, 18)); // NOI18N
        jLabel3.setText("Resumen de compra");
        BackGround.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 160, -1));

        botonAceptar.setFont(new java.awt.Font("Helvetica Neue", 0, 24)); // NOI18N
        botonAceptar.setText("Pagar");
        botonAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAceptarActionPerformed(evt);
            }
        });
        BackGround.add(botonAceptar, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 480, 180, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(BackGround, javax.swing.GroupLayout.PREFERRED_SIZE, 566, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(BackGround, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lblOrigenInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_lblOrigenInputMethodTextChanged

    }//GEN-LAST:event_lblOrigenInputMethodTextChanged

    private void BackGroundInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_BackGroundInputMethodTextChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_BackGroundInputMethodTextChanged

    private void botonAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAceptarActionPerformed
        JOptionPane.showMessageDialog(this, "Gracias por comprar con nosotros");
        BoletoContext.limpiarBoleto();
        
        this.dispose();
        CordinadorPresentacion.getInstancia().abrirMetodoPago();
        
        
    }//GEN-LAST:event_botonAceptarActionPerformed

    private void botonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCancelarActionPerformed
        int confirmacion = JOptionPane.showConfirmDialog(null, "Confirmar cancelación", "¿Estas seguro de cancelar"
                + "la operacion? Se borrará tu progreso", JOptionPane.YES_NO_OPTION);
        
        if (confirmacion == JOptionPane.YES_OPTION){
            BoletoContext.limpiarBoleto();
            JOptionPane.showMessageDialog(null, "Has cancelado el proceso.\n Regresaras a la pantalla principal");
            CordinadorPresentacion.getInstancia().abrirPantallaPrincipal();
            this.dispose();
            //AQUI DEBERIA DE IR ALGO PARA REGRESAR LOS ASIENTOS A DISPONIBLES
        }
        
    }//GEN-LAST:event_botonCancelarActionPerformed

    private void datosResumen(BoletoDTO boleto) {

    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel BackGround;
    private javax.swing.JPanel Footer;
    private javax.swing.JPanel Header;
    private javax.swing.JButton botonAceptar;
    private javax.swing.JButton botonCancelar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JLabel lblAsientos;
    private javax.swing.JLabel lblDestino;
    private javax.swing.JLabel lblDuracion;
    private javax.swing.JLabel lblNombres;
    private javax.swing.JLabel lblOrigen;
    private javax.swing.JLabel lblPrecio;
    private javax.swing.JLabel lblTotal;
    // End of variables declaration//GEN-END:variables

    public void mostrarResumen( BoletoDTO boleto) {
        // Origen y destino
        lblOrigen.setText(boleto.getOrigen());
        lblDestino.setText(boleto.getDestino());

        // Duración (puedes ajustarlo según tus datos)
        lblDuracion.setText(boleto.getDuracion());

        // Asientos y nombres
        StringBuilder asientos = new StringBuilder();
        StringBuilder nombres = new StringBuilder();

        for (AsientoBoletoDTO asignado : BoletoContext.getBoleto().getListaAsiento()) {
            asientos.append(asignado.getAsiento().getNumero()).append(" / ");
            nombres.append(asignado.getNombreAsiento()).append(" / ");
        }

        lblAsientos.setText(asientos.toString().trim());
        lblNombres.setText(nombres.toString().trim());

        // Precio por asiento
        double precio = boleto.getPrecio();
        double total = precio * BoletoContext.getBoleto().getListaAsiento().size();

        lblPrecio.setText("$" + precio);
        lblTotal.setText("$" + total);
    }
}
